site_name: Broccoli
nav:
  - Home: index.md
  - About: about.md
  - Hands-on:
    - ./hands-on/n01_multi_turn_chat/README.md
    - ./hands-on/n02_react_agent/README.md
  - Examples:
    - ./examples/index.md
    - Agents:
      - ./examples/agent/react_agent.ipynb
      - ./examples/agent/react_agent_with_query_engine.ipynb
    - Pipelines:
      - ./examples/pipeline/query_pipeline.ipynb
      - ./examples/pipeline/query_pipeline_pandas.ipynb
      - ./examples/pipeline/query_pipeline_routing.ipynb
    - Query Engines:
      - ./examples/query_engine/pandas_query_engine.ipynb
      - ./examples/query_engine/RouterQueryEngine.ipynb
plugins:
  - mkdocs-jupyter:
      execute: false
  - include_dir_to_nav
  - search
  - plotly
theme: mkdocs
markdown_extensions:
  - pymdownx.snippets:
        base_path: ['docs']
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly